[project]
name = "mpvwall"
version = "0.1.0"
description = "Terminal UI manager for mpvpaper video wallpapers"
authors = [{name="methamphetaminelab"}]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
mpvwall = "mpvwall.__main__:main"
